In [5]:
import os
import yaml
import numpy as np

In [36]:
data = np.array([i for i in range(1,10)])
data = np.reshape(data,(3,3))
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
lab = [0.35,0.7]
i,j = int(3*lab[1]) , int(3*lab[0])
print(i)
print(j)
data[i,j] = 0
print(data)

2
1
[[1 2 3]
 [4 5 6]
 [7 0 9]]


In [38]:
x_cell,y_cell = 3*lab[0] -j , 3 *lab[1] -i
print(x_cell)
print(y_cell)

0.04999999999999982
0.09999999999999964


In [1]:
a = []

In [4]:
a+= ['q']

In [5]:
a

['q', 'q']